### ISSUE TITLE
quotes

### ISSUE THREAD

**Issue by advevo** [zTheroy/theroy-discord-bot#2]
"fart in your panties and mail them to me!!!"

"Advevo made dumb transphobic jokes and said slurs because he is egotistical edgy child but he has this weird cult following that defends everything he does so walroose said some rude shit about him to draw out people defending him and make a blocklist, but she went a little far"

"i would beat up a trans
actually no i wouldn’t
they still have the strength of a man
unless they’re on transition pills"

"17 in the light novel"

"i can't find the clit"

"i suck the shit back up my asshole sometimes if im feeling frisky"

**Comment by zTheroy** [comment]
2 and 3rd are a no-go

1 is questionable

rest i will consider
